[package]
name = "egui-test"
version = "0.1.0"
edition = "2021"

[lib]
name = "egui_test" 
crate-type = ["staticlib", "lib", "cdylib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.26.2"
winit = "0.29.10"
